#!/bin/zsh

# Mostrar la lista de imágenes Docker
sudo docker images

# Preguntar al usuario si quiere correr, guardar o borrar
echo "¿Quieres correr (1), guardar (2) o borrar (3)?"
read choice

if [[ $choice == 1 ]]; then
    # Si elige correr, preguntar por el ImageID
    echo "Ingresa el ImageID:"
    read image_id
    # Ejecutar el contenedor
    sudo docker run -it $image_id
elif [[ $choice == 2 ]]; then
    # Si elige guardar, mostrar la lista de contenedores
    sudo docker ps
    # Preguntar por el Container ID y el nombre de la imagen
    echo "Ingresa el Container ID:"
    read container_id
    echo "Ingresa el nombre de la imagen:"
    read image_name
    # Hacer un commit del contenedor
    sudo docker commit $container_id $image_name
elif [[ $choice == 3 ]]; then
    # Si elige borrar, mostrar la lista de imágenes
    # Preguntar por el ImageID a borrar
    echo "Ingresa el ImageID a borrar:"
    read image_id_to_delete
    # Intentar eliminar la imagen forzadamente
    sudo docker rmi -f $image_id_to_delete

    # Mostrar el mensaje independientemente del resultado
    echo " "
    echo ""
    echo "Para eliminar todas las imágenes no utilizadas y no borrar las que corren:"
    echo "Debes de correr la imagen que quieres salvar"
    echo "docker system prune -a"
    echo ""   
    echo "En caso de error, para purgar TODO (borrar):"
    echo "Para eliminar todos los contenedores en ejecución y sin ejecutar:"
    echo "docker rm -f \$(docker ps -aq)"
    echo ""
else
    echo "Opción no válida."
fi
